--1. 첨부파일 업로드 테이블

CREATE TABLE MP_FILE(
    FILE_NO NUMBER,        -- 파일번호
    BNO NUMBER NOT NULL,    -- 게시판 번호
    ORG_FILE_NAME VARCHAR2(260) NOT NULL,   -- 원본 파일 이름
    STORED_FILE_NAME VARCHAR2(36) NOT NULL, -- 변경된 파일 이름
    FILE_SIZE NUMBER,       -- 파일 크기
    REGDATE DATE DEFAULT SYSDATE NOT NULL,  -- 파일 등록일
    DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL,  -- 삭제구분
    PRIMARY KEY(FILE_NO)        -- 기본키 FILE_NO
);

CREATE SEQUENCE SEQ_MP_FILE_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE NOCACHE;

